---  Geo & Salesperson-related Questions:


1. What is the total sales amount per region?

SELECT g.Region, SUM(s.Amount) AS total_sales_amount
FROM sales s
JOIN geo g ON s.GeoID = g.GeoID
GROUP BY g.Region;


2. How many sales were made by each salesperson in a specific region?

SELECT p.Salesperson, COUNT(s.SPID) AS sales_count
FROM sales s
JOIN people p ON s.SPID = p.SPID
JOIN geo g ON s.GeoID = g.GeoID
WHERE g.Region = "India"
GROUP BY p.Salesperson;


3. Which region has the highest number of customers?

SELECT g.Region, SUM(s.Customers) AS total_customers
FROM sales s
JOIN geo g ON s.GeoID = g.GeoID
GROUP BY g.Region
ORDER BY total_customers DESC


4. What is the average number of boxes sold by each salesperson per region?

SELECT p.Salesperson, g.Region, AVG(s.Boxes) AS average_boxes_sold
FROM sales s
JOIN people p ON s.SPID = p.SPID
JOIN geo g ON s.GeoID = g.GeoID
GROUP BY p.Salesperson, g.Region;


5. How many unique locations are there per region?

SELECT g.Region, COUNT(DISTINCT p.Location) AS unique_locations_count
FROM people p
JOIN geo g ON p.Location = g.GeoID  -- Assuming Location refers to GeoID in geo table
GROUP BY g.Region;


6. Which region generates the highest revenue?

SELECT g.Region, SUM(s.Amount) AS total_revenue
FROM sales s
JOIN geo g ON s.GeoID = g.GeoID
GROUP BY g.Region
ORDER BY total_revenue DESC;


7. What is the most successful salesperson in terms of total sales amount per region?

SELECT p.Salesperson, g.Region, SUM(s.Amount) AS total_sales_amount
FROM sales s
JOIN people p ON s.SPID = p.SPID
JOIN geo g ON s.GeoID = g.GeoID
GROUP BY p.Salesperson, g.Region
ORDER BY total_sales_amount DESC;


---  Product-related Questions:


8. What is the total revenue generated by each product category?

SELECT p.Category, SUM(s.Amount) AS total_revenue
FROM sales s
JOIN products p ON s.PID = p.PID
GROUP BY p.Category;

9. What is the most sold product in each region?

SELECT g.Region, p.Product, SUM(s.Boxes) AS total_boxes_sold
FROM sales s
JOIN geo g ON s.GeoID = g.GeoID
JOIN products p ON s.PID = p.PID
GROUP BY g.Region, p.Product
ORDER BY total_boxes_sold DESC;

10. Which product category brings in the most revenue?

SELECT p.Category, SUM(s.Amount) AS total_revenue
FROM sales s
JOIN products p ON s.PID = p.PID
GROUP BY p.Category
ORDER BY total_revenue DESC

11. What is the average number of boxes sold per product category?

SELECT p.Category, AVG(s.Boxes) AS average_boxes_sold
FROM sales s
JOIN products p ON s.PID = p.PID
GROUP BY p.Category;

12. What is the best-selling product size?

SELECT p.Size, SUM(s.Boxes) AS total_boxes_sold
FROM sales s
JOIN products p ON s.PID = p.PID
GROUP BY p.Size
ORDER BY total_boxes_sold DESC 


13. Which product has the highest sales revenue?

SELECT p.Product, SUM(s.Amount) AS total_revenue
FROM sales s
JOIN products p ON s.PID = p.PID
GROUP BY p.Product
ORDER BY total_revenue DESC 


14. What is the total cost of products sold by each salesperson?

SELECT p.Salesperson, SUM(s.Boxes * pr.Cost_per_box) AS total_cost_of_products_sold
FROM sales s
JOIN people p ON s.SPID = p.SPID
JOIN products pr ON s.PID = pr.PID
GROUP BY p.Salesperson;

15. What is the profit margin of each product based on its sales and cost per box?

SELECT pr.Product, 
       SUM(s.Amount) AS total_sales,
       SUM(s.Boxes * pr.Cost_per_box) AS total_cost,
       (SUM(s.Amount) - SUM(s.Boxes * pr.Cost_per_box)) / SUM(s.Amount) * 100 AS profit_margin_percentage 
FROM sales s 
JOIN products pr ON s.PID = pr.PID 
GROUP BY pr.Product;


---  Sales-related Questions:

16. What is the total sales amount and number of boxes sold per salesperson?

SELECT p.Salesperson, 
       SUM(s.Amount) AS total_sales_amount, 
       SUM(s.Boxes) AS total_boxes_sold
FROM sales s
JOIN people p ON s.SPID = p.SPID
GROUP BY p.Salesperson;

17. What is the average sales amount per customer per salesperson?

SELECT p.Salesperson, 
       AVG(s.Amount / s.Customers) AS average_sales_per_customer
FROM sales s
JOIN people p ON s.SPID = p.SPID
GROUP BY p.Salesperson;

18. Which sales date had the highest number of sales?

SELECT SaleDate, COUNT(*) AS total_sales
FROM sales
GROUP BY SaleDate
ORDER BY total_sales DESC

19. Which month/year had the highest revenue generated?

SELECT DATE_FORMAT(SaleDate, '%Y-%m') AS month_year, 
       SUM(Amount) AS total_revenue
FROM sales
GROUP BY month_year
ORDER BY total_revenue DESC


20. What is the total number of boxes sold per region, salesperson, and product category?

SELECT g.Region, 
       p.Salesperson, 
       pr.Category, 
       SUM(s.Boxes) AS total_boxes_sold
FROM sales s
JOIN geo g ON s.GeoID = g.GeoID
JOIN people p ON s.SPID = p.SPID
JOIN products pr ON s.PID = pr.PID
GROUP BY g.Region, p.Salesperson, pr.Category;

21. How does the number of customers change across different regions over time?

SELECT g.Region, 
       DATE_FORMAT(SaleDate, '%Y-%m') AS month_year, 
       SUM(s.Customers) AS total_customers
FROM sales s
JOIN geo g ON s.GeoID = g.GeoID
GROUP BY g.Region, month_year;

22. What is the total revenue generated by each salesperson?

SELECT p.Salesperson, 
       SUM(s.Amount) AS total_revenue_generated
FROM sales s
JOIN people p ON s.SPID = p.SPID
GROUP BY p.Salesperson;

23. How many boxes of each product were sold by each salesperson?

SELECT p.Salesperson, 
       pr.Product, 
       SUM(s.Boxes) AS total_boxes_sold
FROM sales s
JOIN people p ON s.SPID = p.SPID
JOIN products pr ON s.PID = pr.PID
GROUP BY p.Salesperson, pr.Product;

--- Customer & Sales Insights:

24. Which salesperson handled the highest number of customers?

SELECT p.Salesperson, 
       SUM(s.Customers) AS total_customers_handled
FROM sales s
JOIN people p ON s.SPID = p.SPID
GROUP BY p.Salesperson
ORDER BY total_customers_handled DESC


25. What is the average number of boxes sold per customer for each product category?

SELECT pr.Category, 
       AVG(s.Boxes / s.Customers) AS average_boxes_per_customer
FROM sales s
JOIN products pr ON s.PID = pr.PID
WHERE s.Customers > 0  -- To avoid division by zero
GROUP BY pr.Category;

26. Which location has the highest customer count per salesperson?

SELECT p.Location, 
       p.Salesperson, 
       SUM(s.Customers) AS total_customers_handled
FROM sales s
JOIN people p ON s.SPID = p.SPID
GROUP BY p.Location, p.Salesperson
ORDER BY total_customers_handled DESC


27. What is the most popular product among customers in each region?

SELECT g.Region, pr.Product, SUM(s.Customers) AS total_customers
FROM sales s
JOIN geo g ON s.GeoID = g.GeoID
JOIN products pr ON s.PID = pr.PID
GROUP BY g.Region, pr.Product
ORDER BY total_customers DESC;

28. How many unique customers were served in each region?

SELECT g.Region, 
       COUNT(DISTINCT s.Customers) AS unique_customers_served
FROM sales s
JOIN geo g ON s.GeoID = g.GeoID
GROUP BY g.Region;

29. Which region has the highest average sales amount per customer?

SELECT g.Region, 
       AVG(s.Amount / NULLIF(s.Customers, 0)) AS average_sales_per_customer  -- NULLIF to avoid division by zero errors
FROM sales s
JOIN geo g ON s.GeoID = g.GeoID
WHERE s.Customers > 0  -- To avoid division by zero errors in the average calculation
GROUP BY g.Region
ORDER BY average_sales_per_customer DESC 


---  Time-based Sales Insights:

30. What is the total sales amount for each year, quarter, or month?
SELECT YEAR(s.SaleDate) AS year, QUARTER(s.SaleDate) AS quarter, MONTH(s.SaleDate) AS month, 
       SUM(s.Amount) AS total_sales
FROM sales s
GROUP BY year, quarter, month
ORDER BY year, quarter, month;


31. What are the busiest sales periods (e.g., months with the highest sales)?


SELECT MONTH(s.SaleDate) AS month, SUM(s.Amount) AS total_sales
FROM sales s
GROUP BY month
ORDER BY total_sales DESC

32. How do the sales numbers compare year over year or month over month?

SELECT DATE_FORMAT(SaleDate, '%Y-%m') AS month, 
       SUM(Amount) AS total_sales_amount
FROM sales
GROUP BY month;

33. What is the total number of customers per quarter for each region?

SELECT g.Region, 
       YEAR(s.SaleDate) AS year, 
       QUARTER(s.SaleDate) AS quarter, 
       SUM(s.Customers) AS total_customers
FROM sales s
JOIN geo g ON s.GeoID = g.GeoID
GROUP BY g.Region, year, quarter;

34. What is the revenue trend for different products over time?

SELECT pr.Product, 
       DATE_FORMAT(s.SaleDate, '%Y-%m') AS month_year, 
       SUM(s.Amount) AS total_revenue
FROM sales s
JOIN products pr ON s.PID = pr.PID
GROUP BY pr.Product, month_year
ORDER BY month_year;

35. How does the number of boxes sold vary by season or month?


SELECT MONTH(s.SaleDate) AS month, SUM(s.Boxes) AS total_boxes_sold
FROM sales s
GROUP BY month
ORDER BY month;
